# Generated by Django 4.2.4 on 2023-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_path',
            field=models.TextField(blank=True),
        ),
    ]
